### ISSUE TITLE
[UI CHANGE] CHANGE COLOR COMBINATIONS

### ISSUE THREAD

**Issue by SpywarePersues** [Dhravya/dhravya.dev#2]
Hey! I can change the color combinations of the projects section and blogs section.
It will look better if we change the color combinations.
**Changes can be done in the color combinations of the Project's Cards**

![image](https://user-images.githubusercontent.com/97043346/193577609-ad0d0819-d3fe-44f0-9392-9b148768e1e7.png)

**Changes can be done in the color combinations of the Blog's Cards**

![image](https://user-images.githubusercontent.com/97043346/193578105-d23387a8-229e-45d8-a53b-634e516aed5a.png)

**`I CAN DO THE WORK. PLEASE ASSIGN ME`**

**Comment by Dhravya** [comment]
I actually had a colour change in mind. Thanks for the issue! 

So, what colour combinations are you thinking of?
Also, I have a local commit that slightly changes the colour - please check the latest deployment!
